---
- name: exhibitor | install
  copy: src=/tmp/exhibitor.jar dest=/usr/share/java/exhibitor.jar
- name: exhibitor | install service
  copy: src=files/exhibitor.service dest=/etc/systemd/system/exhibitor.service
- name: exhibitor | enable service
  service: name=exhibitor enabled=yes
