# vim: ft=ansible
---
- name: zookeeper | install
  script: scripts/zookeeper.sh creates=/var/lib/zookeeper
- name: zookeeper | create group
  group: name=zookeeper system=yes
- name: zookeeper | create user
  user: >
    name=zookeeper
    groups=zookeeper
    system=yes
    home=/var/lib/zookeeper
    shell=/bin/false
    comment="Zookeeper"
- name: zookeeper | ensure directories
  file: path={{ item }} owner=zookeeper group=zookeeper state=directory recurse=yes
  with_items:
  - /var/log/zookeeper
  - /etc/zookeeper/conf
  - /var/lib/zookeeper
  - /var/lib/zookeeper/bin
  - /var/lib/zookeeper/conf
- name: zookeeper | configure
  copy: src=files/zoo.cfg dest=/etc/zookeeper/conf/zoo.cfg
- name: zookeeper | install zkServer
  copy: src=files/zkServer.sh dest=/var/lib/zookeeper/bin/zkServer.sh
